# SOPS configuration for NixMox project
# This file tells SOPS which files to encrypt and with what keys

# Default configuration
creation_rules:
  - path_regex: terraform/environments/.*/secrets\.sops\.yaml$
    age: age1jm3etsdme8hwh50sxyzx33gpemt70vqn4zwlsgyscgh86wey4vmsd6lq2s
  - path_regex: secrets/.*\.yaml$
    age: age1jm3etsdme8hwh50sxyzx33gpemt70vqn4zwlsgyscgh86wey4vmsd6lq2s
