# Network configuration generated from Terraform
# This file should be automatically generated by scripts/generate-network-config.sh
# For now, it's manually maintained to match terraform/phases/main.tf

{
  # Network infrastructure configuration
  network = {
    dns_server = "192.168.99.13";
    gateway = "192.168.99.1";
    network_cidr = "192.168.99.0/24";
    vlan_tag = 99;
  };
  
  # Container network configurations
  containers = {
    postgresql = {
      ip = "192.168.99.11";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    caddy = {
      ip = "192.168.99.10";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    dns = {
      ip = "192.168.99.13";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    authentik = {
      ip = "192.168.99.12";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    vaultwarden = {
      ip = "192.168.99.14";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    nextcloud = {
      ip = "192.168.99.15";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    guacamole = {
      ip = "192.168.99.16";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    media = {
      ip = "192.168.99.17";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    monitoring = {
      ip = "192.168.99.18";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
    mail = {
      ip = "192.168.99.19";
      gateway = "192.168.99.1";
      vlan_tag = 99;
    };
  };
  
  # DNS records for Unbound
  dns_records = {
    postgresql = {
      domain = "postgresql.nixmox.lan";
      ip = "192.168.99.11";
    };
    caddy = {
      domain = "caddy.nixmox.lan";
      ip = "192.168.99.10";
    };
    dns = {
      domain = "dns.nixmox.lan";
      ip = "192.168.99.13";
    };
    authentik = {
      domain = "authentik.nixmox.lan";
      ip = "192.168.99.12";
    };
    vaultwarden = {
      domain = "vaultwarden.nixmox.lan";
      ip = "192.168.99.14";
    };
    nextcloud = {
      domain = "nextcloud.nixmox.lan";
      ip = "192.168.99.15";
    };
    guacamole = {
      domain = "guacamole.nixmox.lan";
      ip = "192.168.99.16";
    };
    media = {
      domain = "media.nixmox.lan";
      ip = "192.168.99.17";
    };
    monitoring = {
      domain = "monitoring.nixmox.lan";
      ip = "192.168.99.18";
    };
    mail = {
      domain = "mail.nixmox.lan";
      ip = "192.168.99.19";
    };
  };
  
  # Host mappings for /etc/hosts
  host_mappings = {
    postgresql = {
      hostname = "postgresql.nixmox.lan";
      ip = "192.168.99.11";
    };
    caddy = {
      hostname = "caddy.nixmox.lan";
      ip = "192.168.99.10";
    };
    dns = {
      hostname = "dns.nixmox.lan";
      ip = "192.168.99.13";
    };
    authentik = {
      hostname = "authentik.nixmox.lan";
      ip = "192.168.99.12";
    };
    vaultwarden = {
      hostname = "vaultwarden.nixmox.lan";
      ip = "192.168.99.14";
    };
    nextcloud = {
      hostname = "nextcloud.nixmox.lan";
      ip = "192.168.99.15";
    };
    guacamole = {
      hostname = "guacamole.nixmox.lan";
      ip = "192.168.99.16";
    };
    media = {
      hostname = "media.nixmox.lan";
      ip = "192.168.99.17";
    };
    monitoring = {
      hostname = "monitoring.nixmox.lan";
      ip = "192.168.99.18";
    };
    mail = {
      hostname = "mail.nixmox.lan";
      ip = "192.168.99.19";
    };
  };
  
  # Network ranges
  ranges = {
    network = "192.168.99.0/24";
    gateway = "192.168.99.1";
    dns = "192.168.99.13";
  };
}
