nixmox:
    ssh_private_key: ENC[AES256_GCM,data:+taqrhmObEoNT0MdmkXJT2dmwgABpYfxLA==,iv:0fJbPnFTRXGm+htffkgQiH5/3PWPQ37AGwpFK0DHgGI=,tag:oPKEqhn82OGF4pnYy5kVWg==,type:str]
    ssh_authorized_keys: ENC[AES256_GCM,data:w5pCwz12AZFA+cXHhWdkGjkhvv/8AG15nYG7Vqg=,iv:bjdni6xJVnK5zMVgPnB2jqo7LSwDeSt9JUVzBTiQEoI=,tag:SqessxYwCJxWr115Kt+Jgg==,type:str]
    age_key: ENC[AES256_GCM,data:YUn0jbVJZQT5pFcSIkBjURc=,iv:cdkVSrYYDPf27riZmR1377FR0V6rrvd3pna+/YkM1II=,tag:MQtBxj/1rzmmEGyoWqSJVQ==,type:str]
    password: ENC[AES256_GCM,data:NrOERuh/E2VHWvRFXv0QO6MgPsNc7chwkQ==,iv:V3ZCZY4x0nG4yyCmn1sls1WKl1gZet+nptPY/xNupj8=,tag:Y8vuaREMtLJYhLg+DrTjzg==,type:str]
authentik:
    env: ENC[AES256_GCM,data:ZzJFxn0brWgNqaYIP6DOmpqGrrFu464OkC/0IinMtblSZbK5S+SKEG/Fx7bdvbAbu+SVsMRl8XAU/cQIsp3T0e1ZSh/lAVLZ9qa79A7FdhTI/w2Ftvf9ekRwPgGu+ZlA3ozaqjTmTtfFEqoPovYlSuNwm/DrUxMsSdhgVhxteM+2uB8Xjbzf7ezIJ9i1yDqNueq7CWN8896qatH7MCwFuTmZgeCjWvrfCbPbb/VWCQEFdNtc1afIAtkDQtO5UaRR2EM1XWJLltudWZE=,iv:UJjbdJrbijii4PJgs0quw9dS7BmhZqtelvXJN36WgXE=,tag:fn14toONlqLC8UsUmC3a1A==,type:str]
authentik-ldap:
    env: ENC[AES256_GCM,data:xDjAbpCZlepJw3FDvPhqsLDSwsvH6zm0ynfTHcuT6UCQ2AogRb1kGi/ct3UAKwV7ANqTu/6YeISeCdq/xecPDro3uBYI6vzPAquRMnOoSL3aoYPxWTEcnj1blaoEv1sfJfOqgcmfQvsK3AdL7ZPQKgQxydKlc8IjjwRWRqlMJYyzlU6Zb41bruGR,iv:JGd/ZeGjQNUCOhgP+L3s9msx3cpf10d9+J1jf+nvGfo=,tag:3u1Bsh3sC9WiCPsTVjEpmw==,type:str]
authentik-radius:
    env: ENC[AES256_GCM,data:PbwbZdcCVHgXO/BcgeJPM4THnpjvzBIi6FXucIpcsbZyIaPRcOwsfiAvM3/kc3z23N4Nt8k+KBsxsKn5tZIN5+v4ukkDZUTmXGZBbdZ96ixRCTFcT1gZqp8b/eef+mC93ceO3HTFSZnT+NpD79xSS1CbSqybrAsE3uyZCGbN1zB1IXVlrlrtuuIS,iv:rrbIgbDa9bntv+lPePTehi/zX1ZzTYn4MTEEit3+2NQ=,tag:b9+6F1FXa8ss2HE3JWFtrA==,type:str]
authentik-proxy:
    env: ENC[AES256_GCM,data:UjyhJI+S1KHDyYtoZLFQKZRR+yRFKpUFHzh8NJUHNSr53VvgQ83FA94GIsnsd4hdXXwXUfgoEnlfk81ogKfuU8pvpfYsOmvk2NZFDK2bl2dieumtPP8XzSSDdjMfSmaMhMgPUhuKZVAAtmNWC9bLPBzzPsBQpzTyGV9BDt6io6cFOqNRkA7gZbs7,iv:zY3MEdfqwWGfSdIyJBl8yJqAzEjiddWIRcyVDvHy1bE=,tag:hAtBoDq2RUfMP3JU/w572g==,type:str]
monitoring:
    grafana_admin_password: ENC[AES256_GCM,data:CshRiW1LruRVF63Er8gvOc4eXft1e4FlUW4=,iv:wxIudEwr/5gw1CIFZ49OreZyGwsTFfhnxEmJS3D+i7s=,tag:1CgQUD71DtVkv1QNQBqQVA==,type:str]
    prometheus_admin_token: ENC[AES256_GCM,data:mtnUP8olO5YQ4HA1zb6thnTyL3Oz7DNTn0A=,iv:gHHxOI4y4egHSuBu+l6UnCriCyqDQkBROOQ58fhseU0=,tag:/jCBsK10t3mQz7m3gS/XfA==,type:str]
mail:
    smtp_password: ENC[AES256_GCM,data:8cU+ttNjAH5MPfH2bkePeBycz48YkLo=,iv:BEJUxPHqKifgIqd9oCuhaW6xoPW/8ismRMqjzDkSt5M=,tag:qWCLXk9tL9+J9yqYlBDUaQ==,type:str]
    dkim_private_key: ENC[AES256_GCM,data:hohWgroH8q5OSZ571Cp4hdG+,iv:l80iLURrW0s1v+B0jVun2/obGgERcVPqpD3ir6ueCtg=,tag:ZCeOrilZY7v0HocO2DXdVQ==,type:str]
nextcloud:
    admin_password: ENC[AES256_GCM,data:YvEq8uuy4s6ASEM9BJyjgR/IzVP1qvnkZugAUHtS9wxtKw==,iv:+DcAbe5U7zmnDZx1mwA58irhbIwLmZb4ufjY9ABClM8=,tag:amiG+Y1a2xktIcQdQqcrtA==,type:str]
    database_password: ENC[AES256_GCM,data:euwdkLcE0W8j/F48c58aJYPV4teULnLf6D/f1kkhgw==,iv:90pcymeEPMM4ZpdGy+wCm/L9qDeWXlcHVtfvmWS/DKs=,tag:sYGAj++O6Gw5JVLpi6HH+Q==,type:str]
    redis_password: ENC[AES256_GCM,data:93XJcXEVx6i+4HUHhRbqqsOnssKqKJRfemjop95XjjU1SA==,iv:7MQ9T5KZEqSif6MATbPjDH1wYsuqiXYfLyYzJ4upe98=,tag:vxQ6J3WuyWI597RBJZzAuw==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:J2VqMJse0hIVgZ9s5Y+Rt+9X4SGmJ+EWX7R/36qpoNjP,iv:+eHBEb7h/o9GKN5FdL03HXuQE51pfHdpBGXn/aPv5dc=,tag:8mQ7WBTjMwSQLDzgEARJBA==,type:str]
    database_password: ENC[AES256_GCM,data:dcATcsPgLCo6MXkrxjpCIA+ByjD02zm/ztxgAtSrKTxx,iv:GaqqkxttPOsbqIKpMbu1qzmPQJOaz+K0jOqi9yg9ZWU=,tag:QyqeBcM+fE46g3ZdbDaniA==,type:str]
media:
    jellyfin_password: ENC[AES256_GCM,data:QzC8wtis7VeiPEDEktDAntAqk2qSVRSn6QoI,iv:vlUMqDRj0aSeINRIKnpC6hQ7t1IHwH+DXORxFXZRzWY=,tag:xCzVSlQwcXjaKPlSB7g1HA==,type:str]
    sonarr_api_key: ENC[AES256_GCM,data:Bd0i1CEHeUvfIP02yTHayVNw/3hJHr5q,iv:Os7V88HRu1fbPUOR6/583WjwZPpJ4tD65xnzkZfkp4E=,tag:T8wx2zU2O5UDsQeiMAYwbw==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:1RqbCZmaaWQVUBkMvGDqDqKL4H5hJcCP,iv:XqcMbKt1DLr0bDXhLCUIt1AmvklsrbY7vM+GRXlmblU=,tag:fNftkdyjSzQIHAxXr3SKtw==,type:str]
    prowlarr_api_key: ENC[AES256_GCM,data:AH+Gw/UuI7/iSjmN5JE0eHaw254JTe3owfg=,iv:2GQM03dN8PL1mcXqjJMI/8C9ABh3C6/9TYLgqHnevrI=,tag:AQLRevAsohIa7j7YBB2A+Q==,type:str]
dns:
    pass: ""
backup:
    restic_password: ENC[AES256_GCM,data:oKLb54nd/8pOEzalv/YINFfDMnz3eNETsg==,iv:r07aG7oxUmB19VTG09REx5YOsx6wrGUFWUdKWNxpLaQ=,tag:8EzqgHV5SIh6EZQ4C8f38w==,type:str]
    b2_account_id: ENC[AES256_GCM,data:LqQ26YKCbkNtH+dBWBhz0Mch63Wp6Jw=,iv:MfHyAS27i0EmLqfbIPynY0h102HVp28AZLmjIb5zjs8=,tag:xovWXmW/hngpXQ6fWMufgA==,type:str]
    b2_account_key: ENC[AES256_GCM,data:YPw6aBu9l22DCZsg8r+uLKd84KaEdVYY,iv:fh0mGwlJq37TCcpvzik+CmkT505dJN+R+NxXpuyLDKU=,tag:GNJ4A9xYf9fGrDudJVjGKg==,type:str]
sops:
    age:
        - recipient: age1k9n9pj7y46nk4sta3ghsvd5x9785yrh6fkga4glyex54y2es045qxqpzm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM2Z5NnNnYnJEeUkxRXli
            MkxsUmZ0d2FPdmMxcVR1RlJzaHZObzAxbUhFCnkvUENqNTFYd2Nka2J6VURFc2N4
            cE4xWWxybkxESmJFanpKRmZWSGdIc1UKLS0tIFIvYVhtTzF1bDZwelBOV29iaVNR
            YzBSWmluTzB4NktiSkJhbExQMFRqQVUK/15AB2IsG0mPtonuaCND1N+WLIZSBDW1
            MgyLsfdcFanlPp53ie2GGAoujpxDA7vErJx9v1U4rQdKS7zSaD4F0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jm3etsdme8hwh50sxyzx33gpemt70vqn4zwlsgyscgh86wey4vmsd6lq2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVlMyTTY2TzRxVEZPMVp4
            L1ZqWmVDS0x4VkdUK3FGQmN4VzFRZjRIYmljCjQvbm1xQjQ0T0R1R2FhNXkyWnVI
            UTgrdGlhdWN2YUlhQWE0RFBwNlVZaFUKLS0tIHZXUjVBNmdjYnA1V1EwWTB2cXVo
            dHRZMTFyTkx1UlRzdDZFVW1mbzNHdzQKUnspe4w14U0RwPa57tt7RHFY9CFQvdcI
            slg4ufjNoIXonbyepGNZpnOZ8rb5Mo/cIBM5O+hv4n9X1IhZf4Ngeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T00:38:25Z"
    mac: ENC[AES256_GCM,data:rNkksFmSR9y7PyK/ePHT7pDPakolWwGPMNt3DOwvYvLklzdC/I/iRXApP08SntlAaw1NAZnNnf1I+vMcrOBgHfP7BeqyDUMyIhr2w493Iid5BoaQCO2m01hukrhr4RJnvy/IxZd/yU/Uql7kVYIWYwqHzVW8lzC+PLmRJQONIpw=,iv:BjAVJAjX4tvsSoJFTHcYN5q9JM337fmwg+gVuBPwOUE=,tag:tiSguj7c7w1tie9J7SGfhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
