nixmox:
    ssh_private_key: ENC[AES256_GCM,data:PGffFwWGltO6YYit2RiaYioOXqDDLdcZaw==,iv:yfrIIFisv1aL8O2dOnecpG5jxnFUPIqq5fUM3vxY81c=,tag:5m5SJY2Si2tFU8iTQ4bQzg==,type:str]
    ssh_authorized_keys: ENC[AES256_GCM,data:MeRFFSK0IwHfvd0hawQM/idK4npzVuEHLOOezVs=,iv:HonpAhxpWC6IHACPm0AOO8TVaB2U5g5tvZpBuMcYVnk=,tag:S5FJDoNQGA7JGzx1qN+n2w==,type:str]
    age_key: ENC[AES256_GCM,data:qsG8el5YG5HkuKpM9PYgzbA=,iv:k5rW1xVhbQo1NmvDkxqAr0uqOS+bFD8gHToiA4OaSN8=,tag:smxWWrL5jCj5l09WemSmaQ==,type:str]
    password: ENC[AES256_GCM,data:4QcHuVYP7D7aOoMQfw6W9W/H7NdlcUyWyA==,iv:p4PiwRBENHEJOMlpIWzj+v1j2JYfgO7CmtgFl72tF3E=,tag:j1l3NAwwS3mNliOmzCQXNg==,type:str]
authentik:
    env: ENC[AES256_GCM,data:jo19X7g6d9deqHKdl0bA3563bn26i2Uf3LTd52Ws01UJLkJcZShJAeVHqrzsUXCYa3Qu1yIG2rUmTWulIsTM21/l51Dq9fiU8GvhKedES1EVOl5AV1+LjJHQE36uUO20Y+/eNT7BAJYnuq8ehj6bek9QkAc43CXEIbaWrhkD2TUucFUI0AMIycF+F3NtYHb/qczbUgOZQplrfPrYhr0xpgkhJTYfusPIM7Lw6TFae0u29Gg8S1b/UN8GvYSLuoERFAJaUG57k1nGnlM=,iv:qjFCZobz7joG9XdpDGP9twF7FbPc1EsTnXCefM9Ay8Y=,tag:AjsM5ikLaMVovk2w05GMGg==,type:str]
authentik-ldap:
    env: ENC[AES256_GCM,data:lcwZcTFziQjdi6bntFOtIj3UL1Wlg21HE0+GO0NqNvcly+M1LpJFkyvUIhsj5GCeCr0D6N/7WfUraP+ztex6Jf/BAQT7tfc9QnQWhhJCOjHfAQYxwSiKGdRh3FlQhvaeRATuyq9Ah51fqw==,iv:GIzBIgUHC3TZ2TJ2gfcXXJiv1iG0f5r9TzqcaJiTWQc=,tag:BnzlMkpueuoKZ6uBSsj6qw==,type:str]
authentik-radius:
    env: ENC[AES256_GCM,data:dVx2W+gC4Z44YMopoiZ2iraSydK4GOs0P6zzghDHayd4WFV5l+TEC1DRMi5gf0hpAOnAu3Z4Ej1Jxveukm54kiz44hUFVNRgFiKa24ZMbLp8ggNPGR4cydUxTWh2/RjPqykvSuK60/qaKGcv,iv:6WZ9o+B0J8wGNNFE64OdyngLc5aZVAnu352XzeglgXk=,tag:Zu0J6XOKgIEGIpT72OPbIQ==,type:str]
monitoring:
    grafana_admin_password: ENC[AES256_GCM,data:tyjq3icBGoMLXHcC8AnshuqnusJRidaahUA=,iv:442IRzKcJ3ATKlqkfEJSptcweIscD08Ql0rJTVGELMY=,tag:VqtrXlclOQHRJa3PGBwfkA==,type:str]
    prometheus_admin_token: ENC[AES256_GCM,data:zHszJvh8KyIZaOso7JJSh1ivSbY51giWzVM=,iv:lZ70ITXA40iMVbGuLrmERI5dT1+X58TdW/tq3Wq+pXQ=,tag:4H4Ho2uNovBOTS3o3F9bDQ==,type:str]
mail:
    smtp_password: ENC[AES256_GCM,data:jX8C+dWSwdfgJefIP/SGBn61Y0KJTTM=,iv:/pFOj++gt7JcD2JnudTpS7lhtacrDCziMcQQ5k3BGdE=,tag:QZGnSZhcb5Xd3UtqBzbvRQ==,type:str]
    dkim_private_key: ENC[AES256_GCM,data:XqD5WkiR4thhBprUeLOGZOTT,iv:Clk+MzI11vr61qmVFX3pBUbF4T+FdXYulNHbGAw94es=,tag:m7Be2eU6tJZz2GAYVmupKQ==,type:str]
nextcloud:
    admin_password: ENC[AES256_GCM,data:xscJjqbwXgkdHnOUqeu5omFFoN7XhWuZaTYCxP47SJP1pQ==,iv:3iLWBHKZDTQSjH8dGT0Iy9FZE88Y3fArPNdKZLpgAg4=,tag:8x3X/YIc0xbLPvr0bP8ThQ==,type:str]
    database_password: ENC[AES256_GCM,data:jDQ+0u9hvKEXdRELG7uscxOz9WSc8KPUM9gshHrkSw==,iv:HK3Ua3n2PEIBe0qoS712HX3a3Y5MqAFQGIL+agc+Gzw=,tag:V76jRYDqNMgnNvYZj2SnTw==,type:str]
    redis_password: ENC[AES256_GCM,data:BWhlQqnzvbF0TH4TIo+c/w0gWOFjvnAvzl0YjTPYBHujVg==,iv:5vGOnJfv09UY4LpqzRkh8Z2MW/DrSx5FcHEjUN6jSlc=,tag:8fhnnM95mlXCHVEbvvSRCA==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:YH5fvMUcJPUBBM2mIOPcgSmB5xgk/FiAooXMC37skkxO,iv:O9DBslB1/G8kW6ttA0fC47fspmAByCBiW6AvWXMwmNY=,tag:WFas5PoH3hniRE+hpzIaTg==,type:str]
    database_password: ENC[AES256_GCM,data:sFxISKMWReRW/9BuVyVWPbeaul60JRD+OVLAvP+Gkh45,iv:DZ4xT/lJ+4iItz2HIOBBl/CItHw+X7eiftgEI3RFxVs=,tag:bTiJJc0e6XN59GqtLIvqpg==,type:str]
media:
    jellyfin_password: ENC[AES256_GCM,data:wAB5kaBeS/+BPOEejlVFo64P1UAu1jwYYvhd,iv:O2xEqmU4B0qh5zQ5wreDpGJ+3L1soAK4ArQm6Nn6yMU=,tag:+7N4MnZ7z+5z3bhpvw8SKg==,type:str]
    sonarr_api_key: ENC[AES256_GCM,data:ZTXY8oqDomqxsQUKI2gaOPtKB50n8rKY,iv:sEj7ORXHFciwOkdbbqfD2J/Co1jEHHidhWCAL7yce9Q=,tag:/Zq1KWL43KOsA2T32I7PQw==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:DRx4nCUFe6DGdodAWIrl0GX9IlHdwe07,iv:icTwGNwMdikkhPOs7Q281kBkRnnWr5st42YmqlukAag=,tag:dBl/PyWLBguw2zhwOx96nQ==,type:str]
    prowlarr_api_key: ENC[AES256_GCM,data:Gbwm1o5UPgOMHpPsN5vSuOLrZifKVdKvjxw=,iv:QFHkV3Wmp1+TcS5oKGjY44lQiPo+oU08g7FBqlzikgI=,tag:fOfSLiX6n3QpBnW9N2QsvA==,type:str]
dns:
    pass: ""
backup:
    restic_password: ENC[AES256_GCM,data:8G6DwaQAdr+V1ab2aONRG6FtvdyO3NTsNg==,iv:yAyBBF1pqCuI/ymPizMLiwbexjB6u5QJYts1l52RES0=,tag:gXNVzPsYEAuyjCoHh8DKsg==,type:str]
    b2_account_id: ENC[AES256_GCM,data:eWYJBO3uCKhQzKrnreo6XU7NA7hSqdI=,iv:idZW5Z+M8v7B65mJR1zpZf6pxODG89KBtdCZXe+CjNQ=,tag:UIZSoy4p8Cxtq39zLDT8aQ==,type:str]
    b2_account_key: ENC[AES256_GCM,data:ZtIt1vSBCBxu8i2SE/z5emCb9IZh9Kbv,iv:NoBDFN0psQP24pFV9SszNDfdiaqqtKhH1KnP5w3Sh+c=,tag:1iB2D5UJBAICJ5Qc79aN6w==,type:str]
sops:
    age:
        - recipient: age1k9n9pj7y46nk4sta3ghsvd5x9785yrh6fkga4glyex54y2es045qxqpzm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOai8vcTZrMWtTa2RNR0Nt
            UGVTdTZwQTJ3eFM0aWtacmc0ZERoMEZib0FVCmNpUjZVVXA5NXpYMmNEbEkzTWNC
            alpERVA0OFJ1OUJVbEpFcndrTmEwb1EKLS0tIEhTV3h1QmRBcmJEOURRYXU5OXBJ
            cFdwRnRpVkhwNWExNlE1ZlFwMU9aOTgK70Ff1ECXGcgc4hPk2rDAm+uOkhgQdqSI
            Ff0kqUvwZtfweUKjmpCd1g21+sVkv6RVKqJrYrM81Pm3TKVnltMDpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jm3etsdme8hwh50sxyzx33gpemt70vqn4zwlsgyscgh86wey4vmsd6lq2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOckE4Uks2dHFNNmttMkRT
            Z1QrdHRraTFVcDhuOXRrRkc2R3pQNmFqTkVBCkxxamsremVhMWY5UER5S2ZKTGtZ
            VjhRTFBRc2JOZC9YT0NyekhRT3BWQUkKLS0tIG9aaEZrQmhQbyt0TVd1S2tyb0I4
            TnVUN2pJdUpkL0dRTWJLU0VhMFB4ZzgKlvQ0X2WkuYP/07i+0ehrFbg+T5+yYoy9
            3IS7/hNoEKGctoFmWmgPjbpCCavWTo9Wq1TTnxJv1r1E5eqBpu6A8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T22:37:40Z"
    mac: ENC[AES256_GCM,data:MrEllIyDg8DCHikqYL2ZP3+kcz1MFEF244ydu5uM1Aq1aFXmZpihlYHDGlNsHsvmBpJBiDbaQTdbAg1T/mbLgiGiwCTO3cctxzzyOUGmQF4VqzVHn5uNpAMYBN9tT5pjaM4/X7F5Q91J460a871Rh/+pH3zsHhtVbzlAGIehO5w=,iv:erV54s/v2yrMRK2lTP/QXZlFq0M/M0qFVttJtLLKXPI=,tag:nCnSOEcqZiAiRWIqx0l6+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
