# NixMox Secrets Template
# This file should be encrypted with SOPS before committing
# Use: sops -e -i secrets/default.yaml

# Common secrets
nixmox:
  # SSH keys for management
  ssh_private_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Add your SSH private key here
    -----END OPENSSH PRIVATE KEY-----
  
  # Age key for SOPS decryption
  age_key: |
    # Add your age private key here
    -----BEGIN AGE ENCRYPTED FILE-----
    -----END AGE ENCRYPTED FILE-----

# Authentik secrets
authentik:
  secret_key: "your-django-secret-key-here"
  postgres_password: "your-postgres-password-here"
  redis_password: "your-redis-password-here"
  admin_password: "your-admin-password-here"
  email_password: "your-email-password-here"

# Monitoring secrets
monitoring:
  grafana_admin_password: "your-grafana-admin-password-here"

# Mail server secrets
mail:
  smtp_password: "your-smtp-password-here"
  dkim_private_key: |
    -----BEGIN PRIVATE KEY-----
    # Add your DKIM private key here
    -----END PRIVATE KEY-----

# Nextcloud secrets
nextcloud:
  admin_password: "your-nextcloud-admin-password-here"
  database_password: "your-nextcloud-db-password-here"

# Vaultwarden secrets
vaultwarden:
  admin_token: "your-vaultwarden-admin-token-here"

# Media server secrets
media:
  jellyfin_password: "your-jellyfin-password-here"
  sonarr_api_key: "your-sonarr-api-key-here"
  radarr_api_key: "your-radarr-api-key-here"

# DNS secrets
dns:
  # Add any DNS-specific secrets here
  pass: ""

# Backup secrets
backup:
  restic_password: "your-restic-password-here"
  b2_account_id: "your-b2-account-id-here"
  b2_account_key: "your-b2-account-key-here" 