nixmox:
    ssh_private_key: ENC[AES256_GCM,data:mjFcwOrUzREVPEfhOfow6ZTirwWYBxKE3Q==,iv:zM+xzGM+SSZOEY9m+ENLzBXyLiWGTaheSKtrDDKsuM4=,tag:4eMqdh3Uak1PPTId8UUPIA==,type:str]
    ssh_authorized_keys: ENC[AES256_GCM,data:Lk+hD/roXXZjOCvcPefa36UVvIvxadP1eyJf+F8=,iv:P+U+c/0M3XLh5Gn5svt82kXrKkeESQBlip0xjZJYFPY=,tag:eS2iu8sQJpd/Szf4n/79yA==,type:str]
    age_key: ENC[AES256_GCM,data:L5KY/XjSHXMW2gPMPwCbR18=,iv:Dkfx/rfQcKNob5IgVCUEToc/4FGbJM1Ierpr/UraKVg=,tag:+sgh7ZlJp9RFO2DDCO7StA==,type:str]
    password: ENC[AES256_GCM,data:ApyARoyjAzZPn1xDzDaMr+GcnpsAc4vjLw==,iv:CqLIAfTD6eMnNB+yZG2530Wg4D/Veni75mQDmJOtDIU=,tag:iiuMrMCDmya1SXM22x1s3w==,type:str]
authentik:
    env: ENC[AES256_GCM,data:NxAQXxtS8EcWqv9HCRlEKXs1rkmOJ+tJ/j0XOr1j/TdD0rBiXo8kgNh1SZVPZ6K7+KcpeQFiOXdYjTCPrltX4f5ZvdYRX3ocYF9aMe7blZGJStETstohaV8HyK0+/9Y96Dq7VzOlXYFhJEkfzkYL3A8ulshq8eWHncR7s8u6Qju48VOAauD2aTYYc5tIA8NvXmkiCy5fBbggofTMyxPQ+d6nSFfXBOfIjznzB0Qnlg15oF8w5yblEWeAmStb+Aqa78qzyWb1LqzXHpwkmiXPPPB5v4ocJGC+qpL/wv+6ec7HPeF0TUlv6qW1JMZx9HkJrvMkoH3+hNEkV6Zp6Klc9XmeF7+Vh4kVXfQQA8nGW660l/EREs8Vog55nlU6s7RmDEXnish8fj16kzNJRV2g/h0eqwqMlpJxWcmCRLTx87ybbV6CR/tWA6dNt7qIW08To5d5iQjwmV5q7cB0GK65Xg9Vwwm0bhCvwW37t1flcsTeNzzrPv8OoaOii/jX77hdaTmPL7qRsfVWQZ1YOUXWr5j/MaEJS9GP2urtbHI9oC4FHxp+krDvuL0ydL2I9PUZeJt1vTqkDvVlNg0PqoVD35QRdI3WmCH0UqXWtd1FmbIgUUlHnojiuEI0HwJJ0xfxotXoiXkReBaYvF3sDd8=,iv:s+2jLfJ7YlLue4bmEdf6c4dIePIY3dxMeX7YvsLpG9Y=,tag:Pf/+kYTmM9Qov3fPcv5GUw==,type:str]
monitoring:
    grafana_admin_password: ENC[AES256_GCM,data:Lk3oEpquSZTeXAQK7kl4hmmJWKeSCnc62Z8=,iv:AhYe5ZR5hV5IfGorNSDA6oHkVaZ2BJDM+JqPpqaC7H8=,tag:LR3oZxICemZiZzh4cmRUuA==,type:str]
    prometheus_admin_token: ENC[AES256_GCM,data:z0PNNE59nUYLPO4Hrhx4OQNjre2rF+djv8E=,iv:fh+SRU7PlsYsPQrSXHqH757WRpC7A5fEhSjh0ZXHLlM=,tag:fpF7B2Thnfsk14RTEKGnAg==,type:str]
mail:
    smtp_password: ENC[AES256_GCM,data:aN3d1p45/23d0vkNfDxuw9BY1n6wtlw=,iv:LOfs+PPLw0ph/a8X+XI9/ZoXxWd/T769s67KiETvW5g=,tag:4DdMrelz/F3cFOyoRMv60g==,type:str]
    dkim_private_key: ENC[AES256_GCM,data:G7aSfZWvZqcNQgKGEdfrQ5YA,iv:Km9b+MxwGWarEnVkegxF1kNzCFcBRNP5x5MKiyeQoS8=,tag:8JRO+hjiQx6hApR0uHchdw==,type:str]
nextcloud:
    admin_password: ENC[AES256_GCM,data:Nu6fmFhReGEVd62U6bMET3Ohov3QjsrLZ2pchwAe+BrxgA==,iv:/S1EhCw6y6rgqcOvh5v7wf9oHInxKzcA80srM6Xt/pg=,tag:2ZLivkD5ExrXVsSuTwIXNQ==,type:str]
    database_password: ENC[AES256_GCM,data:jDu/VIfqnkI4ogJtcLKpZzTclXDyItHmeHbRha9ZeQ==,iv:yiE3zfLhK2bb1ScckIs9At4aYrP8TIFHj2BDIETRQVw=,tag:ADcKUGN8JpJ5ITsytjMQiA==,type:str]
    redis_password: ENC[AES256_GCM,data:hjxYjNwaJZ0QTSufjRpIICE9rfXRRJDVk0SkjofajKm+Jw==,iv:GMhkifuTMowouANYGCPzNctdi39tH2EnZ40yKrPjIu0=,tag:R7y80A241LKyGuIWUyoseQ==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:ZNX29MWGMm8OZEn9ESYK44rz96e7rx+70bShk41o9AxS,iv:Dwc3IyW7kSNOeOKXKBZ3H5yfDqQJ4ui3rqOrzdLZMTc=,tag:g1ryrNrcJKvhTLThGz+YJQ==,type:str]
    database_password: ENC[AES256_GCM,data:dQYEUxT+Dw65BlQc9nYi14ZIlsRaajFK5IFyxU8hApZ/,iv:/ZsjfuvrVRzXiw2cGE9EXEZNaz3pspC2MjkBoUpHkOY=,tag:WNKLcMAfraBm7dAOC2FoNw==,type:str]
media:
    jellyfin_password: ENC[AES256_GCM,data:HnEl61tkAWKVyOv+cHg8CSNJcE/kvxUXzV5x,iv:iowoi35XBmRmtT0vaDX+5IQjl3hk1vbF3tBqj+08UFk=,tag:nKsYafuw0gueR/jA+M+BYA==,type:str]
    sonarr_api_key: ENC[AES256_GCM,data:TxvPIi441x31oHIyyR8tV5LPBfD8UPP2,iv:KCratKL4MPJDXQX5xahCtV0/rshEmhxQFmPBiA5LVJA=,tag:GijT3yNghDEQZspWD0nUZA==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:6Dt7qRqrbQxCwTxOWt6Zyt+foMNJaecN,iv:i02mZRLzawnABTVT7XDYlPHPpZmm9uIRs8x5YxVlYjg=,tag:qb6WDVYUevoRpF1BZM2snQ==,type:str]
    prowlarr_api_key: ENC[AES256_GCM,data:PP/jfIo0ke3eRk8tSVyu8pfmRyQluXhM/hk=,iv:OisPkqombixmSyn90YGOv30TAY27fDuMyOGREOHOICQ=,tag:vmRe9ojiN51WkIHNDFe9bQ==,type:str]
dns:
    pass: ""
backup:
    restic_password: ENC[AES256_GCM,data:A+bBEaWXZuH5NcLmHQ494AOUppDHwiaLYg==,iv:nPjxmNgx3eIhjOhQjgwbLLOd8iEEqNOpSHhLZAd1vV4=,tag:UatESJsOux8mONzT7ApjWg==,type:str]
    b2_account_id: ENC[AES256_GCM,data:qTMgTZvehEZkqsQI8sX4QHizRCq9HPA=,iv:Tc++5NLPTnP4yS6JnVYF7KToeG7xCGSqFde1tulzKeY=,tag:2KCYG906ST0SDTRl9cqfxg==,type:str]
    b2_account_key: ENC[AES256_GCM,data:YUH3cp8uyT+98oTmNt5QBv8p2GUtJ3tL,iv:hQzeBCGwRmfclfpiYRZmGfbptampKpiEe2Su1/HiSdc=,tag:ExOr7iD+cs01Gid/MTAMnA==,type:str]
sops:
    age:
        - recipient: age1k9n9pj7y46nk4sta3ghsvd5x9785yrh6fkga4glyex54y2es045qxqpzm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MVRiSmlFb2pma0M5MEpN
            Q3M5TG5nb1hDbmgxNzJCOHFtL2RId3MrR3dNCllNY2tGY2EyQ2JsWXcrdGxUNWR2
            RWRIbmlBT1cyRmYzL0ZBVmN1WjE4Q2cKLS0tIHNuSnVSK0JOTm10SzMxVVNXdUUw
            SzN3a0J0YU1tWlFHam5QOWQyR3I1dm8KY96zOlWxRIMTRl81yKBBbl+FFWxWJZwU
            zVdK653iJcb9vqUiUNCYHg6sZt7ppjLzGy3LWllZKk/Zxte3PiUj0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jm3etsdme8hwh50sxyzx33gpemt70vqn4zwlsgyscgh86wey4vmsd6lq2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y3MwM2xNSlprNy9hdXpM
            T3VQR0gwNGg3WnpkWGRUUUJiRXMvcUg0ekdJCk9VTXdxNy8wa3N5WGxKZGlLdDEy
            bWxrUUU4Vmhpd09RbGtNUFVJb2wxL1kKLS0tIFpCb2JDaHhqK05mc2J1Z0p6Y094
            Wkpod3RjSkE4RmpvYzIzNU0zUzEyTmcKXx5DouM5H3PLQgWiNXLBronDOSHaY8aE
            dA+tW4lJRBVrF4mvlp5hn2dODe3qJimIJgMnXz4uMjbCkvFnJhOXEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T01:11:29Z"
    mac: ENC[AES256_GCM,data:7W+nePJop3ys297WcuKCIZpz20tf3WGs1n6h5jHNiFJMNqvo/n3Ux36hJ4UnWX+RazJpd5RBFs3exdnXSPCEdmH9AgV4q60StIF4u26n2IeCoDl2mAKy6f8AclOBuYJqdJVHRXMz7g620x9nyqQcn0v3z3w/SRX3oL2D8iuo3lg=,iv:ImN3+LLxB4s/og76FOjsPuInH8PsNtBGaMoMoln3LyE=,tag:6rXbGF6dQgC7dOpmzW1ODA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
