nixmox:
    ssh_private_key: ENC[AES256_GCM,data:7y8EWsxE3Pxb/+GQmNAoJLCOiEfupueMEmrxARxdNGp/X4Zcu09JMzBCBNltvE0kKv2UWAOwKYORLHDEdDD8RMJnVoea02RfAumBhHrF0Ggwl2erSINt9ErvJKEaUSql32likYpY,iv:jzr/8NuKfpXQ6g9VsmCK60CzpVi7G/10ZAWJ1NkPbGI=,tag:CNAQ+IfXQXQjsk8k/SjR9w==,type:str]
    ssh_authorized_keys: ENC[AES256_GCM,data:QxBuDkQK73suUa8K6MikEa3itTB43fzCoXA9kemoKJ934HllnUNf3/93pMFqpSIHkZ4XxAQYVP5il/p3/zk1NxaieJu/4jS6K8yOK+qIW5IXHQCjuTWIBBaJpVA6Z8myOzpcUO+gK6KUBKWiClu/1ylH+jE8HYsBAqzudnYplB8a+aYFM7SbZ89hYvhMSOOIWQkLYeI4v9H3AB/0BaNjObZ33De5AzLdHmisdIPgXJYHoG8R1nIFMIbKL0jFTlzk4PD4g/2MOorxqWyhHAbNK3E6HwfHhVUCfu+YmU4A4UdchHdrrS6gbnKLAzdsify/Ux1Ytp7UpBXEsyJz88RKkXpEe9RrfDq7MMGvsQNMS+MxNr3/ULFNI5UM01pWKdzs6grBYjRxk1iBnrB8hx6ZzM8PWSyZHg4wJNVBhnoBqis5f7HOHV6kH453TLCXh0SIy1bebdXx4l6IxyR/TDlib2+KAsvYIcEssj1C5cnYspnHE1n3gtB709E85j1pktM+Mh9C+Fg+NteQ121XBf5Tru5ievn9uoVKny03PkPC1vak6x7tG6qR2Q78P6vb7Drr2UG4S2bUnr7bQRMNlNgVL3tvNmX8hYi4IaYrpR3oICrs//MZS33wKRDsPv/OMdc7sjW5EQ4EFsIN0it1IPCtkxnDPJPihcEwwZUunkzxIv5cYNaLjMLt/yU9xKsVMwWoJJ6mnModGlvNeAmIP7z8Rtkfm3fWfIFSKCYGkBhRA/LULsJTa1b62Su7u1C5n2XJuhqF/Z722xOuwGWMFwbresrxd378uaDnwUfCd8/VhDfVsvKzA4bxcTGZfsWfG4S3UFNWfSpozy9yb7smaCwAgfr6k4kgH8NW19uBSWoPkARVPJ0GM4w+GA0qkX2PN773js0jpYru3bbyKr0nlwfDJPBzkuf65xINKC5Gs79hUtn6NbNn5Fq6AC+3+oZkLrTI9rGbCelRVjIMRgXHO73BYAteo6KEth8R+OHMB9eJ9zDasCBIaK4VLWdgJLxv5Fmw9O6D7NUBqzx7SDycMqoqZm8fc/QauDWY7Vch1xCqoKdX9N6VCexGHLXmKz3Wl6s7W4SNpZ15IKxAKH+SuiwZ,iv:iYAHULDkvITcLDLafDowcjdqCKKBwLKM/3MiTG4ontw=,tag:x+NEwCWVFft4Pgsc3InDuQ==,type:str]
    age_key: ENC[AES256_GCM,data:00w4Y9L4krxcm3yLfEdLRg5nNzBMlx/+lEPEboR02P55/l1/R6bmpI0wC7hSvYGDjB0SJte2ZCZR0jUVrc38ZeFO+pRrFzVIwnW/iAv7iioeGcoCpe1dWkvIaPIVN7RITyEFNQ==,iv:/KDrd3NmZGB/JON97kCesJphglpAXF6KP0F9M49tzxE=,tag:j3yAH2VyFQT8ZQXguB73RA==,type:str]
    password: ENC[AES256_GCM,data:SU+JPzOX+Y3SwRQ=,iv:eiLuyahFhHW/6lOu2A+mFY4PR0xeymDyKZT9ePMsosg=,tag:D8SDVwdnuO9aq/psAjIjCg==,type:str]
authentik:
    secret_key: ENC[AES256_GCM,data:2W1r/xzBN7zy7v3I6GzAtwsc9YHxG9VTSjFB,iv:ldklt25kaSh7A0ULXVUcrssFEeQjU3g+//p7q7fgN0A=,tag:RNUqMPPyNnxb6zPaLtEqhA==,type:str]
    postgres_password: ENC[AES256_GCM,data:9ds9U8+FJUeO9gsDWOitduZ4V0PXz953Llp4,iv:zddiEYqMw8mt1rAqRjWu4IGE22TJY8B4l5DT87fynZU=,tag:CuDYa7l/p2PVvYyGKVazhQ==,type:str]
    redis_password: ENC[AES256_GCM,data:IE9ateC3RPGIy15Le+r9ECU3yEaGkO1w,iv:8YBt3f7XdsYaoulCHf0m2FTb7faJuTQzW9NJGtDztGM=,tag:oi5roxn8oykcsEDJfWEiiw==,type:str]
    admin_password: ENC[AES256_GCM,data:RjQf8npvudRFd9u4sJo47v+Uxd7hVkH5,iv:msFu7yENQhAZCk39UhxEUr2Jfpg7XvP/xGchm/Q0fHg=,tag:UYcZckDwDSImMHD7z8LPzQ==,type:str]
    email_password: ENC[AES256_GCM,data:eziwd+l/ssMNyoLx+v4BJMx1Aj3qe8/9,iv:njtjtX411+3/bepVC6NTZMPaz5R0kcEvLkz8OdWVp3g=,tag:pO6rEK62WDDcM8MUrg5umg==,type:str]
    outpost_token: ENC[AES256_GCM,data:CPaV6FcBSHqyCIa8q0c0SORKfadr7e8=,iv:s3nndqvQ0/TFnXCVCB6tTkyA3dbIJIGdxc396oy9cr4=,tag:bRDuY7b0Tg2vwGhAjtDdGA==,type:str]
monitoring:
    grafana_admin_password: ENC[AES256_GCM,data:NxyQzqpDUzCRdc8pyGmk9MVDGUsS8JitHz0WG/eiGFU=,iv:TIdQ17Mg3vTN/HtMJVpCkG/unHj9FCKQ2gqnsgG+RIM=,tag:NJG2kfVfRYBfnCIUdbyBiQ==,type:str]
    prometheus_admin_token: ENC[AES256_GCM,data:mdOngbA/Kmvhl+HrOmsDkapbbKKhjLmmWgCBN58OhHc=,iv:jYR0FG5rJZGBXklpay1AzQm07haZC1EcEI7ixolqNTc=,tag:SZiG7D2nY2Jxv4FKW5v+Mg==,type:str]
mail:
    smtp_password: ENC[AES256_GCM,data:XkHcmZsqELFQIqVtNG+1RrfEBBo2TMU=,iv:ZNziGyxXM/e1acgmCBmqmwxB6oVMMxE/Mk7nAytY8l8=,tag:OBIPdkwn67sks0IUPSdKqQ==,type:str]
    dkim_private_key: ENC[AES256_GCM,data:suNU8tuBWHwGK+WNuI1fP/tfNMhz6gs9rkQy4mtnCeL/nBDgo0y1npHnmKEp0+H2denBnZSN8SQcXPSoOaN4FE9flLAm3E9iPddUvwhu6Tn8eEr1j5xO,iv:7IDKMyTGHLKC1FjqKFzsv8NB1gQ+WdQTzbqnJrPcWmA=,tag:gOsYrCA44Vg3eQbXnX+M6A==,type:str]
nextcloud:
    admin_password: ENC[AES256_GCM,data:xK2UFRz3E+bin5kfiXeRfqZ/dR8bhYqQupyN6hkV2IBmXg==,iv:dotgriNWwLJtIab3ZL5TOx+O2LsouQIKDdMDCIQ2N8Y=,tag:Aa/Mux+xzTMH2CeVZ93NRA==,type:str]
    database_password: ENC[AES256_GCM,data:3gyxzJ7M96M+WxPC/u1esF2hvnodeok0jfywEHl6rQ==,iv:1+9qU+bpuJPWDBhWWYrUg1H4J8a6Jl5ZDK2+CPKp34Q=,tag:WsPve6J6o7QFvxqUAvAnWg==,type:str]
    redis_password: ENC[AES256_GCM,data:2GlC28+zkTCZth58wjMEfuCYiU4epQxByl1a11yTuO5yCQ==,iv:K/8k6Kb1K/yRjGqaTAMsz4cS/HT3tyf8SnFFLSuPNtU=,tag:CMFjMew4A2pxl9LGdQGeRw==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:sxokLDS44P4BvKl41Eo/tbNelR77W48PDiHkI53aI6GJ,iv:vJaaplyU7hSb8FcoYd+bGAWOOqlHjG9fUtW4RhmaHYU=,tag:EzBdBSaM/Lmm+vTuVYBeuA==,type:str]
    database_password: ENC[AES256_GCM,data:pkTBsOxez2wVp6UZaM0Copz57VubcQOGjYLAIDp6LnOf,iv:8witet9DAkPi+iltTA7JEdMNVB4Gptv4qp+6KHFeKBw=,tag:mCZ5LNrQl7G2EVVTXEhlHQ==,type:str]
media:
    jellyfin_password: ENC[AES256_GCM,data:/H4JbQ3/I0ApAYkDXILXHWsY0VIKZNnZUup1,iv:Gh4h6GvBiM9gQAK17X+5TwW40B1N0pVMrx9U5EczELQ=,tag:bjRE5OuJAnTflp4BgTkMKA==,type:str]
    sonarr_api_key: ENC[AES256_GCM,data:jOBXR4+V5bKeeyIOxM62/JIwqK+ITXCS,iv:SZjLJFPLQncBrx2LPmhZX1IO83Cki0oG3LIkUvzWxrw=,tag:JfvAP21ExrNYqbyR3u3Z3A==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:4XQoAy9ggq5a8z4GhVlpHMqSAGvSiM+R,iv:Vt8jBPh49pr4Tbr63Nk79mzkjjbRZvU974ehtsR4y4c=,tag:efz1j0R94hRj7TW3Hj3dOw==,type:str]
    prowlarr_api_key: ENC[AES256_GCM,data:RbVSw+DW444LtkC+K55zEbhYRtyR5+qbxqU=,iv:z8L+XRRI0w3sNXDDJUW6Lky/T1myBgXwz/GSQO8Xcxs=,tag:3EhkV9oE34Hpoy0+Vu/0nA==,type:str]
dns:
    pass: ""
backup:
    restic_password: ENC[AES256_GCM,data:mHDoZQU4isHGDRgR4JatmwmHmLpf08VrOQ==,iv:AdbO4W8YT/QgNmNV5jPJ7TCt99SiZeBLtJ1+aP0Z6E8=,tag:horwb9HtPIVELdKJjyyPPA==,type:str]
    b2_account_id: ENC[AES256_GCM,data:0SHE6izIQ4MS7lyAaXQDox07A+nwfhE=,iv:SwnfhpFrIXiMJqpmtxGESfulsdTFZktGkMWoR1SCbKI=,tag:PU/26ui+YbvE+FNBAohwtQ==,type:str]
    b2_account_key: ENC[AES256_GCM,data:Rgf14p4/FFcknxt/q7WWEI1C7HbbVNCC,iv:1rFtUQTh3YL//K35Vb994JkyG2zsE8NwmV46CAZvrY0=,tag:/jV5v00p/mwsiWG1d3Hh4Q==,type:str]
sops:
    age:
        - recipient: age1k9n9pj7y46nk4sta3ghsvd5x9785yrh6fkga4glyex54y2es045qxqpzm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbEpwSmZPNTE4OHBjMGVh
            cGkyWElHaDJYWjdhZnZHdmRDTWMzaVo2WWxNCmJUZ2pmczZ3YW5oWHh0MkNmR0Vt
            U1ZmVWJuMGIrYS9tYWxIWGs5NTl5YVUKLS0tICtyRGtMeWozUUVIMVVUSFJMWDZ5
            d0s0ME80UTg2R2dPVks5bkZVZ1RwMmMKNOkKzU+MxDVahmhN2CZI0waAGPN8Jvo4
            /C6EOU+rjKw6AzzEHV1oe3HOVNO2D4uOqKfrxqW9aoKTMGpnwj3b9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jm3etsdme8hwh50sxyzx33gpemt70vqn4zwlsgyscgh86wey4vmsd6lq2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT3Frc05SMmdDODJJVW10
            eEs5b0FlNG84MmYrbEpvWU9HVmtteGlYUEhJCjhyY0pyWlZZbnBRNjJlNXgwNWQr
            V0VZaUVoaHRyMGNjeUZEWDdScFlsVzAKLS0tIC9CblFMUDM1cGlnT3RiRTRrTFE3
            aEJOcTVBSit6L1ZtS01hQ0hzYmc0Y0EKdLBF+K7mgH6tA5EFebgfASj+covD8KJ+
            6Z9UXtNIoNDdwg0adhmvHZRJUmg3j8WSaE8AMUYYB+aUY21Uy5+BxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T21:45:50Z"
    mac: ENC[AES256_GCM,data:FTklT9hH9kP3aJ5M/nwyKblQuXbVMXhCuCR86TLwBfRK/vSh84YSbdMSyo4ruj1WRP+AxEfpcmI2MGLyR43mFKDnaWMdImTsKz/dKDbYvlYcXhQQyYb36AaWiaxjHpXoixA1b2eHMpRa7GHZj/A33jbZT3K44tMtWzQMlsQo9Fg=,iv:mHNGJ0whEnb9tPeS+Qkwr+i4d6kTKehleKAosmr3KBI=,tag:3XeqVuPsrDqv7B0kzzJY9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
