nixmox:
    ssh_private_key: ENC[AES256_GCM,data:NMOO3dTYM1sDO1l4A90h2Spd15z93eW/Ow==,iv:lQaXdS1ZYoJ+E1zcK4BRZqOhHYFE5aBFB2IVEODDaEQ=,tag:IxWMN+O+y7QJBolLrCcqBQ==,type:str]
    ssh_authorized_keys: ENC[AES256_GCM,data:bImWiWAKZNYJpGBANCcW5ElDo7mqPteRsmfy0fI=,iv:l2YKmyknJ3kG7DzKMpp2FTfsp+USWI+bHzn93TLA1YM=,tag:wQnMCK7bIGP3A6MatvB8Iw==,type:str]
    age_key: ENC[AES256_GCM,data:nmPDlJbtFVLZ7fYCrL+zUtQ=,iv:latGX7cGCLVl/KwN0Au6y6mn2nTq+9rlh4KJV82Tx1Q=,tag:HIZWj0qcGowr5agiDANy/Q==,type:str]
    password: ENC[AES256_GCM,data:RLr1hOJWsAVONdOWtS+dPfPqWsYPXIXLMw==,iv:i0B/JMPUFwStJxBzgbO53d41a/mFdDhFrY+sY2PXQJw=,tag:D29PDuxGo18BV4i8sOZUiQ==,type:str]
authentik:
    env: ENC[AES256_GCM,data:GMs21i7BDAgJtorJctm4SxBLzI0y47SPZgD9lE2mFLfSkFSg48k0KyUJQgC0dhGq6YHpcLIRrkbjsTLS/0ZMIINS5opMS0B/kH4Q0v0wCj5imTGQLkfvy6F9+Ik3HpuRVIsIlNtLoEReKxOmta/KUgxPCDNFcBi5iMkguxEepLYw+jy2taIuyHxAnwETDtsHvzG57fnyRtQKTTIKMO7J+iT+FipsZOKXJZH0HDZ2C9+iJLBdD4EwGRvZzHoRrxIxGxRVDVJ4sOSDNZe/Y6abhjM8g7nYBkG9klzBi2qwp+aCKkQKkuU7sz1v7/QwSrzzhcbFrZjh0uEI6HpD3AmwmPO5HGwKQphn7qFiJvVhciraI06zQcuaCwk//G0H1tpmTrcmLjFAq8afMQPlDjm5Gm1kUQHOil2LDWFFgk/wUTB4rtdEZ8J3srMbpTepATaxbuakIHP/ufLRTJcksT0ufq4=,iv:6LcvgxOuxjsvrvAXqeotQyxIoZ46aYCMpnCZzFDBorM=,tag:1A9z+igYrTc5kL6nXpRQdQ==,type:str]
authentik-ldap:
    env: ENC[AES256_GCM,data:xcz80/bstewePjm1GR+qxAvKxVqGR5fwmzBM7Fppu9ZXzJ4E7aONkanJcnaJtVEC+3+j1BRAvk1C0jgRWldFvqIM/ilzPsOvU35pNDHsxUpzH7mptfvqiHcUSSTgETot92L+FWDxDR71QNevCDDt7l7HcOSy4n7YiQGKDOGyeKvTJtN7gfAv2+K5,iv:7wYoS3OJMQlW077xX+P/4qB+7XTmdNTMiNyQKKMKGis=,tag:BoYMgighXWdQoUAvP8zZQw==,type:str]
authentik-radius:
    env: ENC[AES256_GCM,data:pfvZWkCk8fKWnlO0sbbUvu9DKOOFXraWgnCVSR2Zx261wfI2JQVqDYZpj1c0aWAKYkMBJNjrpAjFmNRNr/IBawdpZIQa6kbbJBSYmfoNc90KuvBtWt8n6/a146gEnIibJsojJNMUmNLWqBmcf89nAmEblYYf1mKo7DlWkxb4xrtFMHDasmegzZPq,iv:vw4kDrnjwsf7b+JdqhaXJSIpXeh7lstKIE3+0MVROyI=,tag:+Ka71GsDsBAsiaccVs44OQ==,type:str]
authentik-proxy:
    env: ENC[AES256_GCM,data:lHRvOmnncz74g63GaeCI/IXL5DpW5LIKWhNu4wY8yT2xs4jxo/WuloSUzWoBJe/2txUO22Du01O6YoRGi9qSHRAax8bf+5v4IIU1WW8IDhQLr5vjWta2DUUq2VtnPqK1eOUZyX1kb6vtaa9S1nPerDUYRFBKGdplgKXi+3bEBz07o3k2yms8Iif/,iv:2uLQ5OMrhQNs31HwAB1NEYQv2jOPGjkpxB2hmvHsm3M=,tag:OEEDb9G/dT3ffsHduSaU+Q==,type:str]
monitoring:
    grafana_admin_password: ENC[AES256_GCM,data:CKuS51apQ16jhREO57cq6mz4fSryPOjaHDQ=,iv:5N0WCBeqNpFV0m3biAZvtekfOsLfElJf+XnLr9yJfEo=,tag:kCfX8PAEeMamunOgKS6bJA==,type:str]
    prometheus_admin_token: ENC[AES256_GCM,data:ykuxsaGAOcBCsQYv3R6I7mdyy47d0EIp+kw=,iv:KganKadfxZL3QdX2IRe7QM9ItwcRUKvSbFpdC6SNHMY=,tag:62mWUF55XbufOIiSHfTC9A==,type:str]
mail:
    smtp_password: ENC[AES256_GCM,data:ex7omKZRC/wr2v94JFCEVQyKUtgKJ2E=,iv:anflQD79i5nXAY4jV6nQCsDLDqjzsmhkYHmmTxI6iQY=,tag:czJtpuy+pkftSOwaOnLEnA==,type:str]
    dkim_private_key: ENC[AES256_GCM,data:i3i+IY58RDG0tgRLF1l4yBBa,iv:MC5+pR0UPowTH2ccXKslIycKhAZEAhFNKp5TC6JxE1Y=,tag:jK2F2WC7GkTWHJEOuHPJJg==,type:str]
nextcloud:
    admin_password: ENC[AES256_GCM,data:16/7XubkassilOVmOjYTufSJHoZR5jIA+ZuHft5wCv+A+w==,iv:Op0efsoOfKU1/KnApHdsExeoZld/oTCZ/aHnVXi3MPM=,tag:vnDCE23QWOg6bpqmEM+8PA==,type:str]
    database_password: ENC[AES256_GCM,data:GTRaY9+L41BkNiC6eDNKDlMPITuO6UR9X3jK2RT5Ig==,iv:DF4IYmHf5mseA5djhiQBc8S1OnprRpoNoL7PDWbJKig=,tag:48h0JpcuzBU2hqHY0RjMrA==,type:str]
    redis_password: ENC[AES256_GCM,data:lWkVyvHInPdbxA2dUY4kOTXbD2tAlyfgtmwOzZ8As2PsaQ==,iv:DQnh/WxNIier7BsMChsE7hoMhl5Z5e1E3FXzL4QGbXQ=,tag:OZfFojP7Nuq11LxhD0whsA==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:gPM1jind68H5gK9LAazNvazejAQh3sVCaq8+YXxV5697,iv:5qxK9vu07VkgENEAadDqR2KPnzmoHsCaWJZ4YxxZFQ4=,tag:tbraZMwUg5Xt90BSmTwQrA==,type:str]
    database_password: ENC[AES256_GCM,data:/W1CeDGpeJGmIR//Wk7+4GhEulFO2/3haqosrwz4Fofp,iv:XfbdWyLfcbQ2a6/bypIAVXr+AMfgUFTss8O2hhz+/+U=,tag:i7hvRZNpCbtmamJPtjkKEg==,type:str]
media:
    jellyfin_password: ENC[AES256_GCM,data:s13ZvG2CYEb+KUH3vMcx4ega3yZc3KaLUcPR,iv:OL8FDlj3xqKKHstQFihmP3zabPRu2j869gZy7kFbSjs=,tag:dRi/1RzDF4IlR+owZxS5eQ==,type:str]
    sonarr_api_key: ENC[AES256_GCM,data:ENzAjeRwhK84JChNyye/xrjj6sqC+EeT,iv:wShLG+XM0GnSbUTrMPKfJsVyoesOQUghdnynGg6zZi0=,tag:iDX0nvNmTxPPSHhuyiELNA==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:CG8NrcGbP9dyO9GjEsTs3ewEFHtTfDhG,iv:o/nmJijQkVnBg9/UlvkZTf32EPRHvKDcvSaV13ySBnk=,tag:XY757n9r2dn6BgaDWeEmtw==,type:str]
    prowlarr_api_key: ENC[AES256_GCM,data:sJG4FtYEobPtKMlyFBXmby004gvpqMWuwIE=,iv:I/WW2T0c1Ak4AHLBy9lVk7d9iWdRYOM4QnJui7DnvUw=,tag:bvMuLtqs3vJ6aPOTJhYr1Q==,type:str]
dns:
    pass: ""
backup:
    restic_password: ENC[AES256_GCM,data:vxyl4dn4hoR8176EyUpZ74yEBueQA7N8ow==,iv:diDBB5NfxjLIs+sCQpOKDlHdeKspgI9WtfnmFInBaNk=,tag:aJFVXyFHQ4mnyFoALgwhzA==,type:str]
    b2_account_id: ENC[AES256_GCM,data:L8k+OfjnzZgWTdE7C5sntacU3dG1uOs=,iv:bvIcVLKsIWBcfLyt60hcgyWs9zZtfYtAPKjl8COXNFk=,tag:czOt+lSSi7aEgsgN9m8UfA==,type:str]
    b2_account_key: ENC[AES256_GCM,data:pUQqcWDfY6lF9N2XQU9IpoX3knGy/l0Z,iv:jKXZQ+4ibJyDnnu0n1/HJ77tLT9QbwuWSBpclX/ynDE=,tag:VFnKa4+2TlyzeqOf8G78hw==,type:str]
sops:
    age:
        - recipient: age1k9n9pj7y46nk4sta3ghsvd5x9785yrh6fkga4glyex54y2es045qxqpzm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRWxFdlRQT0NHQzFlWlhH
            L3QwaUh6N3YxcGgvQzhDTUlYbVMyU0dTaGprCm5SbEQ0eUtoL0tpL3JHUFNZQWVz
            OG9WdWVMSHhxeG9qZTUyMS9hNDcxblEKLS0tIHduVFFXZnU5aVJBd2NGTGF3ME9x
            bkdtU01acHdoNUlNOGF0eTlRQU9mcGMKG/X4x+wkbxysZjrh72Njy0DntgbQ0lkk
            PPZflqlwpNM+e/7ikZZPXVpDwA8ngD3BKda5+tFOYW3QSX5jsBEdyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jm3etsdme8hwh50sxyzx33gpemt70vqn4zwlsgyscgh86wey4vmsd6lq2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb0RtU0NvVVY2QzM3N2F4
            TUE2V1g3a3ZnclZObDgzUTFCSm5iNCt1RVRNCjMxTm52cG1JNUNLVVdGRmJWeUVK
            eC9uUWUrcWVWVlM0eTg3SEdOcDNwZmsKLS0tIGJpVjFVaVkwK290ZHBWREI0Z2ZJ
            bzM1My8rRW5CYmJDM1pmeGNVREZGTFEKrWa4Fa2rLEI7vmTnMb19g19crkLXjtQo
            +Yi+KiEbx26SkfAjd3XKGAJBiyPfK2FTWeFwS3LwknpbcJdTjXXSAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T02:28:00Z"
    mac: ENC[AES256_GCM,data:+KWADRXbtzHnSMdf34OQV/wPRzQHi4KKXKttni3mNDAJG17BrMKfwSlUir/maLlrGqCw8sHpBfkc6vG/tZ+3aY5zqnCZ80D9KefJVPsBK4t8AG0MuTk7ipyVNmmQB3WbHhzzbKrXgC2Vt3DH7ng2qKpppKcB0m9t3PcClVWzzIA=,iv:FOms2qKGrnBZXBYqPewKbneQrBSLlFCmytZ770hBFM4=,tag:eZtZwoIsU6gThEgpKYIekg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
