nixmox:
    ssh_private_key: ENC[AES256_GCM,data:vjvaiwBbasI+9XyTym/CiYadoF54ywQh7A==,iv:+YAkDl0BcuQ90/Yf3yUoMJfNnNIdqFAfgWVs7oVnST4=,tag:a3gQV66iNXvPb1aReNG/2A==,type:str]
    ssh_authorized_keys: ENC[AES256_GCM,data:ui0R5VbCnVoz+lh71jE3hWFNPPQS/IZwyBGE9Ss=,iv:vZONFcHG/ivzlRoEUGXxJhOE6EbPqmzgFdH5s572jIA=,tag:QZA0ujSANd9lUO7OEvpHGw==,type:str]
    age_key: ENC[AES256_GCM,data:u8jmlkSJvFzHfxh8np6vlgo=,iv:TCDdBiqrT7UHTrr47XDtTm3uzzPk/Y48sLA76LEQtIM=,tag:oFeniOeUMdonVDz2DwPl6Q==,type:str]
    password: ENC[AES256_GCM,data:klyeNMfkhj9Rs/fqzR4IZBX+CrIy/8qItg==,iv:xXVZtQzce6GJQe4M0KFj8GLmMmi5lImkN1I9qFDMX94=,tag:qaHjaa2OpEnqoqRdDctayA==,type:str]
authentik:
    env: ENC[AES256_GCM,data:1DNnc66uHB8w7h199r59XZ8gu1ZxnQlA7mR1UlCkAMjFgsAWPYilMQI5mMHLaec6s3OXFrWUucWVmDW+OGJwXVgYJ/VNhIJZxK500tkCa3IF6m3IkxFhUdgLC9ai9pzYHJZ9DNksABmIhL6s/xjmTJvHnFieExdMmYQxIsC0Ou66VU+cGRGwm7YINfKRL4ZUFQpVY54xyvM3SW1pO5pp8NqAc9m69/iLEkxtXE0TFqWMZSU35nBFh0//TbOABguWSy8i/cgz1j5wJOKxc5xCIVEtH8qup5BNqEXfDaJBUE0NzpeKiWdqgc+ItsIanJZUTxXpaD82382SI7NFuTWw5fdwMqJMU8Aec0ZHslYgGdjSixinm5TmbNvdKqrpj/3e3tJlYM4RdMWKALmVjA9XzCtC1ruQeZyJJMJQpCabF5rH6lQN4Tqn99OybUTgVxTkETwVqITL2Tp2uQNwDAL7L2zlkjzrwsfy+BizX53CpN4cR4H9hg1xzL33ku/BeF+v4cVzm/Ek/+fsGN1XaWeU3qxElBU=,iv:ncw+tbYDym6DCAh4TcfZvasf3WRYgehFpqI5ISaz2Fc=,tag:3Yri2x2KGTQpe+UbJDnaIg==,type:str]
authentik-ldap:
    env: ENC[AES256_GCM,data:SNj5H6UIKL9qYKZdexJkiJ6hVbQTzBCgn3Gj3PHHcM50U0zW+RXgXaKIyNuilIKmDeToy40CJQBwv/EmDZmN1T3LbLRqLqiNa5D7MRowN6hhVDrrf9Uwcrq/yc5oGgKAB3z1N3EEqIkCDnP8bobpEFExClL1Qq8JDQjcF7R2DIhc00tFZhnNo+KYzDGmEQ==,iv:b4LN3yxnUsZH00X+95Q88jk/GMMp7XqseEyunrUvdNc=,tag:8xEFdOaYnRIq2wdGSy6BaA==,type:str]
authentik-radius:
    env: ENC[AES256_GCM,data:rLEdmFsS0I5+ky75tZkk53l6IvOcforwvpSJcQYUCKDZOmN+nVT/+T8bIyN7vA4uq6+5YPEQEp5dUIfp/HRws2TwYH/j1CPBT1iwH8p2/lmUinJDDI3x64b971U6VbvhHNWZvBcorz5Qa/Pf8ggSL50TXHwivvXEm8wYUzYfm/UjTuUO8k/70Y3U2l1zLA==,iv:GRqBdAaZl+EHcNxkOOic1itnYBiajNr7M+nNFk2alaY=,tag:5I1j2dh7PhK4IUflCfLHNw==,type:str]
authentik-proxy:
    env: ENC[AES256_GCM,data:UqQRh+OM+orxR2amcd/kg58HSF7vZrgBonFygW30wSd3WrMYTEmYyOlXrL04bBTuMe62zXBwERpGm69os1exD3rqVjx3d1QCFShLODQeUyhridK5SLWYNhSEniktSh0ow4YmMUqyHV7TkT4b9ePK5HtdbzZorTBbYH5prRrbAB/BRRY1MwzcbpUQQEDsEw==,iv:ldIzvmxsVlHeCSxkmBSBe0Bm2Og+EE+y1FLzmBmtby4=,tag:XJz33B/8fplLjWLOo9RyKw==,type:str]
monitoring:
    grafana_admin_password: ENC[AES256_GCM,data:XKWdVwgeYfGu3rzvK77TOJosEVgLgFpitZQ=,iv:ycS2uAFTfT/R1Yiu3PI0cdScDRbEVZ5OpH5og7AgaO0=,tag:tNFp8H46C8QTrk7wkkt8jQ==,type:str]
    prometheus_admin_token: ENC[AES256_GCM,data:6MorJlkRDY8pFVBWjWD1zI6UzxsrKydYYhY=,iv:qJ8VI4Yb9z8R4PZct9iC3AF3nBodS/aHY6UIuZPnexU=,tag:fjY6DIssXJxxXVTUvHfpKA==,type:str]
mail:
    smtp_password: ENC[AES256_GCM,data:kmcyoXFsZxYfQo3InoG9zpPGjqaMDz4=,iv:K3U+l0jVwYmYCqZmUnVfirn+AeyxyDPKv8UjA/Mr7jg=,tag:Us5lgwW6V2FooVt+bWBNiQ==,type:str]
    dkim_private_key: ENC[AES256_GCM,data:nrI1wLHJBZHEBHZ97W/gak2t,iv:wFRKPuQanVobVnoLldHY0WTCMoooLO7uxgu4iEPisRA=,tag:SHyqcSNYQt5q4TQQov3IJg==,type:str]
nextcloud:
    admin_password: ENC[AES256_GCM,data:PG9zLp0iTi/+X7vYv+aZcZb6BMjdh0hn/ODf3Wz97Ex3og==,iv:DlGaVFTRq7u++WJWQWhm6hNq+ha2zj5yVw322W2+wC8=,tag:nl7eVn6qEb2eT/Uau7O1Ow==,type:str]
    database_password: ENC[AES256_GCM,data:xUrWo0gTW9rLLVsoPTdkedfye9QgxpVQ2/72Pk8aag==,iv:+r6ydJDTF0fVYoW7nYB+HJF2h7d+w7nzPmfpMmlCVRw=,tag:upD8ENpC5hR0L2hAg9/1kw==,type:str]
    redis_password: ENC[AES256_GCM,data:7uJK7pArI+IDWTUAzmmwh5VKWTgqk5ZKpMiB3VxTIUzKKw==,iv:YYk8O562OWmlhA6zLP5XhJ8DURzoAQQWCQbVtueWUj4=,tag:svf4Li+gn1lSsM2VBg3NXw==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:DLVzFmtW8jgtYU+gJSpQkO9DkW04M1iOM8HfsFj58a+g,iv:WD2GeFnwD5QG41yVjmcsCZ5BlGqEZRFLy2G2ST4y5ZY=,tag:XEustr5y78ZsMR0BT1+8oA==,type:str]
    database_password: ENC[AES256_GCM,data:vUz+BboyvEEcFG6kiNT12GfFfsZboTiHd4S+qP1t2w7Y,iv:mR/AMuT7alnX5go9GNVpIw0rrg2MjaNHZ0Nn2YlIaQw=,tag:2+u6Myk+t7j1vKZzNciJFg==,type:str]
media:
    jellyfin_password: ENC[AES256_GCM,data:6Fhc3d9eB+XI+ehOMVckvQIpXrlih/j8V1r/,iv:ymi8+NusuyVMaYwS+ZCuhkedLCHsuy9El4sQfslphF4=,tag:OWgWfs73oRhQ4YjGMJtrTA==,type:str]
    sonarr_api_key: ENC[AES256_GCM,data:rdpn0aEOEVoWy61O7Vj1o0krYucL7BN7,iv:NZu/FUs93Up/6q0HZ9ScA56WHTcrrZ4Fd6ZUL3sYhfc=,tag:b2CsPq+xp5JAKmq1LROmUw==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:71Mt6NBsyifaloz6xVIjjnOLFly9Va6s,iv:Yu8LE1N3p8lutVWONRffPcGmnyCXSidWXagMgHGM2gM=,tag:QizIMjxqhz/Yl3kPnhfUZw==,type:str]
    prowlarr_api_key: ENC[AES256_GCM,data:H1PQkiqftTjTZJAf2aoyzqa1e2v7LwII7+Q=,iv:6dUL6QLPdbYgdg6z0+2ia2LxA+UUY9DJ3UVFgWqNU7I=,tag:33YsWFws50GmFn/6Vniayg==,type:str]
dns:
    pass: ""
backup:
    restic_password: ENC[AES256_GCM,data:yFEvVwqenZhdladJFtVZZ4YS8HXm+IbtOg==,iv:6YabrVW4H3mTWZ5lcd78xWqyx9XQyHehuM3G92JJfTw=,tag:iZQvTLgDWe/DuImaO4mROQ==,type:str]
    b2_account_id: ENC[AES256_GCM,data:dyaB/R3jhoutAbdpASH8MOv865oN4rQ=,iv:SSppLSTjPeDeCDKPy2T+PT8Lj4cHYD9BZ+6WABhqo2I=,tag:CzFcH2vuMcjuHR1C+sGnqw==,type:str]
    b2_account_key: ENC[AES256_GCM,data:JwQ/BTmSheo5KPB2zekLI8RqXyFOS/pc,iv:eWBp6ZhQ5fLq7PPV996N+pe9oNtpOBA7lvxi7Tir9zo=,tag:B0VIf973zqV3Tvanqo5ysg==,type:str]
sops:
    age:
        - recipient: age1k9n9pj7y46nk4sta3ghsvd5x9785yrh6fkga4glyex54y2es045qxqpzm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUXFQOUI4SkRBSE1YOVh1
            MW1zb3hkanF2ZlRFYm40N2Y3c2QyV2dzV3hBCjlpTGNDZ09taDN3V2J3b3ZDNGNJ
            YVJaeUUrNUducGhpTGg5eHlqbTVRK1EKLS0tIHNtb3phTk1uWDRKNHYyYUNjUnpk
            R3o0WW0rS01tV1h1bEFiYTVkUm92cEEKI+XXRSHNAcujac/i1aGqXPmdJgl8rft7
            kMHNw6AJsfcsVl9PqdTnViBi1+ls2nMMaRuJrGqj4Auf31ZPC3SyhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jm3etsdme8hwh50sxyzx33gpemt70vqn4zwlsgyscgh86wey4vmsd6lq2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN2lwWUJMdHZUNFB1M0Fy
            U1h3NVFnV1BhRStFWXBPY3FuaktBTjg5dEFzClJRTEZVYmgvbitCNWNSR1RVYkk5
            MlpTNWpjSE03emxCakxJNTFaaTJhNWMKLS0tIDE2T05xMUVreFdENkowYjJVdVN3
            T1hkWVhsWURXM3B2TlZ5Vzc3citoR2MKLNhEO/u6k+lrUrktffqNq5E1yj8GTmQs
            D2/bbrWcU2klGB/N6Bb4nt+1NtkLrNzTNc/K+wUfMst9d+Or47YkHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T03:04:21Z"
    mac: ENC[AES256_GCM,data:UsoocUCgrSjhlZhD6WJQKGZYVDhv3PxQdEmdase5FrvJC3D5UtlwIYPxYaSdFc7s6WxGCSNEaBjPsKwvulbFZ+dNgmAqu4gao5wUYrmP4hM96V4U40CBxpfwvNrxWuASU2MlFk7iObxPkp9DmMmQgd9+BhynG7K/h+ip0kBaCBw=,iv:IvlNCXx8RXn4AozUAPQUnUGwz//2RdJygdFQCjUXboA=,tag:aNVqrReQK8/lJHmCdIChdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
